source 'https://rubygems.org'

gem 'berkshelf'
gem 'droplet_kit'
gem 'foodcritic'
gem 'kitchen-digitalocean'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'pry'
gem 'rake'
gem 'sshkey'
gem 'test-kitchen'
gem 'webmock'
